//
//  StationLocations.m
//  shmyki
//
//  Created by Robert Wagstaff on 24/06/12.
//  Copyright (c) 2012 DWS Limited. All rights reserved.
//

#import "StationLocations.h"
#import "ShmykiContstants.h"

@implementation StationLocations

@synthesize trainLocations, tramLocations, busLocations;

- (id)init
{
    self = [super init];
    if (self) {
        trainLocations = [[NSMutableArray alloc] init];
        tramLocations = [[NSMutableArray alloc] init];
        busLocations = [[NSMutableArray alloc] init];
        [self addTramLocations];
        [self addTrainLocations];
        [self addBusLocations];
    }
    return self;
}

-(void) addTrainLocations {
    [self.trainLocations addObject:@"Aircraft"];
    [self.trainLocations addObject:@"Alamein"];
    [self.trainLocations addObject:@"Albion"];
    [self.trainLocations addObject:@"Alphington"];
    [self.trainLocations addObject:@"Altona"];
    [self.trainLocations addObject:@"Anstey"];
    [self.trainLocations addObject:@"Armadale"];
    [self.trainLocations addObject:@"Ascot Vale"];
    [self.trainLocations addObject:@"Ashburton"];
    [self.trainLocations addObject:@"Auburn"];
    [self.trainLocations addObject:@"Balaclava"];
    [self.trainLocations addObject:@"Batman"];
    [self.trainLocations addObject:@"Baxter"];
    [self.trainLocations addObject:@"Bayswater"];
    [self.trainLocations addObject:@"Beaconsfield"];
    [self.trainLocations addObject:@"Belgrave"];
    [self.trainLocations addObject:@"Bell"];
    [self.trainLocations addObject:@"Bentleigh"];
    [self.trainLocations addObject:@"Berwick"];
    [self.trainLocations addObject:@"Bittern"];
    [self.trainLocations addObject:@"Blackburn"];
    [self.trainLocations addObject:@"Bonbeach"];
    [self.trainLocations addObject:@"Boronia"];
    [self.trainLocations addObject:@"Box Hill"];
    [self.trainLocations addObject:@"Brighton Beach"];
    [self.trainLocations addObject:@"Broadmeadows"];
    [self.trainLocations addObject:@"Brunswick"];
    [self.trainLocations addObject:@"Burnley"];
    [self.trainLocations addObject:@"Burwood"];
    [self.trainLocations addObject:@"Camberwell"];
    [self.trainLocations addObject:@"Canterbury"];
    [self.trainLocations addObject:@"Cardinia Road"];
    [self.trainLocations addObject:@"Carnegie"];
    [self.trainLocations addObject:@"Carrum"];
    [self.trainLocations addObject:@"Caulfield"];
    [self.trainLocations addObject:@"Chatham"];
    [self.trainLocations addObject:@"Chelsea"];
    [self.trainLocations addObject:@"Cheltenham"];
    [self.trainLocations addObject:@"Clayton"];
    [self.trainLocations addObject:@"Clifton Hill"];
    [self.trainLocations addObject:@"Coburg"];
    [self.trainLocations addObject:@"Collingwood"];
    [self.trainLocations addObject:@"Coolaroo"];
    [self.trainLocations addObject:@"Craigeburn"];
    [self.trainLocations addObject:@"Cranbourne"];
    [self.trainLocations addObject:@"Crib Point"];
    [self.trainLocations addObject:@"Croxton"];
    [self.trainLocations addObject:@"Croydon"];
    [self.trainLocations addObject:@"Dandenong"];
    [self.trainLocations addObject:@"Derebin"];
    [self.trainLocations addObject:@"Darling"];
    [self.trainLocations addObject:@"Dennis"];
    [self.trainLocations addObject:@"Diamond Creek"];
    [self.trainLocations addObject:@"Eaglemont"];
    [self.trainLocations addObject:@"East Camberwell"];
    [self.trainLocations addObject:@"East Malvern"];
    [self.trainLocations addObject:@"East Richmond"];
    [self.trainLocations addObject:@"Edithvale"];
    [self.trainLocations addObject:@"Elsernwick"];
    [self.trainLocations addObject:@"Eltham"];
    [self.trainLocations addObject:@"Epping"];
    [self.trainLocations addObject:@"Essendon"];
    [self.trainLocations addObject:@"Fairfield"];
    [self.trainLocations addObject:@"Fawkner"];
    [self.trainLocations addObject:@"Ferntree Gully"];
    [self.trainLocations addObject:@"Flagstaff"];
    [self.trainLocations addObject:@"Flemington Bridge"];
    [self.trainLocations addObject:@"Flinders Street"];
    [self.trainLocations addObject:@"Footscray"];
    [self.trainLocations addObject:@"Frankston"];
    [self.trainLocations addObject:@"Gardenvale"];
    [self.trainLocations addObject:@"Gardiner"];
    [self.trainLocations addObject:@"Ginifer"];
    [self.trainLocations addObject:@"Glen Iris"];
    [self.trainLocations addObject:@"Glen Waverley"];
    [self.trainLocations addObject:@"Glenbervie"];
    [self.trainLocations addObject:@"Glenferrie"];
    [self.trainLocations addObject:@"Glenhuntly"];
    [self.trainLocations addObject:@"Glenroy"];
    [self.trainLocations addObject:@"Gowrie"];
    [self.trainLocations addObject:@"Greensborough"];
    [self.trainLocations addObject:@"Halam"];
    [self.trainLocations addObject:@"Hampton"];
    [self.trainLocations addObject:@"Hartwell"];
    [self.trainLocations addObject:@"Hastings"];
    [self.trainLocations addObject:@"Hawksburn"];
    [self.trainLocations addObject:@"Hawthorn"];
    [self.trainLocations addObject:@"Heatherdale"];
    [self.trainLocations addObject:@"Heathmont"];
    [self.trainLocations addObject:@"Heidelberg"];
    [self.trainLocations addObject:@"Heyington"];
    [self.trainLocations addObject:@"Highett"];
    [self.trainLocations addObject:@"Holmesglen"];
    [self.trainLocations addObject:@"Hoppers Crossing"];
    [self.trainLocations addObject:@"Hughesdale"];
    [self.trainLocations addObject:@"Huntingdale"];
    [self.trainLocations addObject:@"Hurstbridge"];
    [self.trainLocations addObject:@"Ivanhoe"];
    [self.trainLocations addObject:@"Jacana"];
    [self.trainLocations addObject:@"Jewell"];
    [self.trainLocations addObject:@"Jolimont-MCG"];
    [self.trainLocations addObject:@"Jordanville"];
    [self.trainLocations addObject:@"Kananook"];
    [self.trainLocations addObject:@"Keilor Plains"];
    [self.trainLocations addObject:@"Kensington"];
    [self.trainLocations addObject:@"Keon Park"];
    [self.trainLocations addObject:@"Kooyong"];
    [self.trainLocations addObject:@"Labarnum"];
    [self.trainLocations addObject:@"Lalor"];
    [self.trainLocations addObject:@"Laverton"];
    [self.trainLocations addObject:@"Leawarra"];
    [self.trainLocations addObject:@"Lilydale"];
    [self.trainLocations addObject:@"Lynbrook"];
    [self.trainLocations addObject:@"Macaulay"];
    [self.trainLocations addObject:@"Macleod"];
    [self.trainLocations addObject:@"Malvern"];
    [self.trainLocations addObject:@"McKinnon"];
    [self.trainLocations addObject:@"Melbourne Central"];
    [self.trainLocations addObject:@"Mentone"];
    [self.trainLocations addObject:@"Merinda Park"];
    [self.trainLocations addObject:@"Merlynston"];
    [self.trainLocations addObject:@"Merri"];
    [self.trainLocations addObject:@"Middle Brighton"];
    [self.trainLocations addObject:@"Middle Footscray"];
    [self.trainLocations addObject:@"Mitcham"];
    [self.trainLocations addObject:@"Mont Albert"];
    [self.trainLocations addObject:@"Montmorency"];
    [self.trainLocations addObject:@"Moonee Ponds"];
    [self.trainLocations addObject:@"Moorabin"];
    [self.trainLocations addObject:@"Mooroolbark"];
    [self.trainLocations addObject:@"Mordialloc"];
    [self.trainLocations addObject:@"Moreland"];
    [self.trainLocations addObject:@"Morradoo"];
    [self.trainLocations addObject:@"Mount Waverley"];
    [self.trainLocations addObject:@"Murrumbeena"];
    [self.trainLocations addObject:@"Narre Warren"];
    [self.trainLocations addObject:@"Newmarket"];
    [self.trainLocations addObject:@"Newport"];
    [self.trainLocations addObject:@"Noble Park"];
    [self.trainLocations addObject:@"North Brighton"];
    [self.trainLocations addObject:@"North Melbourne"];
    [self.trainLocations addObject:@"North Richmond"];
    [self.trainLocations addObject:@"North Williamstown"];
    [self.trainLocations addObject:@"Northcote"];
    [self.trainLocations addObject:@"Nunawading"];
    [self.trainLocations addObject:@"Oak Park"];
    [self.trainLocations addObject:@"Oakleigh"];
    [self.trainLocations addObject:@"Officer"];
    [self.trainLocations addObject:@"Ormond"];
    [self.trainLocations addObject:@"Pakenham"];
    [self.trainLocations addObject:@"Parkdale"];
    [self.trainLocations addObject:@"Parliament"];
    [self.trainLocations addObject:@"Pascoe Vale"];
    [self.trainLocations addObject:@"Patterson"];
    [self.trainLocations addObject:@"Prahran"];
    [self.trainLocations addObject:@"Preston"];
    [self.trainLocations addObject:@"Regent"];
    [self.trainLocations addObject:@"Reservoir"];
    [self.trainLocations addObject:@"Richmond"];
    [self.trainLocations addObject:@"Ringwood"];
    [self.trainLocations addObject:@"Ringwood East"];
    [self.trainLocations addObject:@"Ripponlea"];
    [self.trainLocations addObject:@"Riversdale"];
    [self.trainLocations addObject:@"Rosanna"];
    [self.trainLocations addObject:@"Roxburgh Park"];
    [self.trainLocations addObject:@"Royal Park"];
    [self.trainLocations addObject:@"Rushall"];
    [self.trainLocations addObject:@"Ruthven"];
    [self.trainLocations addObject:@"Sandown Park"];
    [self.trainLocations addObject:@"Sandringham"];
    [self.trainLocations addObject:@"Seaford"];
    [self.trainLocations addObject:@"Seaholme"];
    [self.trainLocations addObject:@"Seddon"];
    [self.trainLocations addObject:@"Sommerville"];
    [self.trainLocations addObject:@"South Kensington"];
    [self.trainLocations addObject:@"South Morang"];
    [self.trainLocations addObject:@"South Yarra"];
    [self.trainLocations addObject:@"Southern Cross"];
    [self.trainLocations addObject:@"Spotswood"];
    [self.trainLocations addObject:@"Springvale"];
    [self.trainLocations addObject:@"St Albans"];
    [self.trainLocations addObject:@"Stony Point"];
    [self.trainLocations addObject:@"Strathmore"];
    [self.trainLocations addObject:@"Sunshine"];
    [self.trainLocations addObject:@"Surrey Hills"];
    [self.trainLocations addObject:@"Syndal"];
    [self.trainLocations addObject:@"Tecoma"];
    [self.trainLocations addObject:@"Thomastown"];
    [self.trainLocations addObject:@"Thornbury"];
    [self.trainLocations addObject:@"Toorak"];
    [self.trainLocations addObject:@"Tooronga"];
    [self.trainLocations addObject:@"Tottenham"];
    [self.trainLocations addObject:@"Tyabb"];
    [self.trainLocations addObject:@"Upfield"];
    [self.trainLocations addObject:@"Upper Ferntree Gully"];
    [self.trainLocations addObject:@"Upwey"];
    [self.trainLocations addObject:@"Victoria Park"];
    [self.trainLocations addObject:@"Watergardens"];
    [self.trainLocations addObject:@"Watsonia"];
    [self.trainLocations addObject:@"Wattle Glen"];
    [self.trainLocations addObject:@"Werribee"];
    [self.trainLocations addObject:@"West Footscray"];
    [self.trainLocations addObject:@"West Richmond"];
    [self.trainLocations addObject:@"Westall"];
    [self.trainLocations addObject:@"Westgarth"];
    [self.trainLocations addObject:@"Westona"];
    [self.trainLocations addObject:@"Williamstown"];
    [self.trainLocations addObject:@"Williamstown Beach"];
    [self.trainLocations addObject:@"Willison"];
    [self.trainLocations addObject:@"Windsor"];
    [self.trainLocations addObject:@"Yarraman"];
    [self.trainLocations addObject:@"Yarraville"];
}


-(void) addTramLocations {
    
    [self.tramLocations addObject:@"1 - East Coburg - South Melbourne Beach"];
    [self.tramLocations addObject:@"3/3a - Melbourne University - East Malvern"];
    [self.tramLocations addObject:@"5 - Melbourne University - Malvern"];
    [self.tramLocations addObject:@"6 - Melbourne University - Glen Iris"];
    [self.tramLocations addObject:@"8 - Moreland - Toorak"];
    [self.tramLocations addObject:@"11 - West Preston - Victoria Harbour Docklands"];
    [self.tramLocations addObject:@"16 - Melbourne University - Kew via St Kilda Beach"];
    [self.tramLocations addObject:@"19 - North Coburg - City Elizabeth St"];
    [self.tramLocations addObject:@"24 - North Balwyn - City (La Trobe St west end)"];
    [self.tramLocations addObject:@"30 - St Vincents Plaza - Etihad Stadium Docklands"];
    [self.tramLocations addObject:@"31 - Hoddle Street - Victoria Harbour Docklands"];
    [self.tramLocations addObject:@"35 - City Circle (Free Tourist Tram)"];
    [self.tramLocations addObject:@"48 - North Balwyn - Victoria Harbour Docklands"];
    [self.tramLocations addObject:@"55 - West Coburg - Domain Interchange"];
    [self.tramLocations addObject:@"57 - West Maribyrnong - City Elizabeth St"];
    [self.tramLocations addObject:@"59 - Airport West - City Elizabeth St"];
    [self.tramLocations addObject:@"64 - Melbourne University - East Brighton"];
    [self.tramLocations addObject:@"67 - Melbourne University - Carnegie"];
    [self.tramLocations addObject:@"70 - Waterfront City Docklands -  Wattle Park"];
    [self.tramLocations addObject:@"72 - Melbourne University - Camberwell"];
    [self.tramLocations addObject:@"75 - City (Spencer St) - Vermont South"];
    [self.tramLocations addObject:@"78 - North Richmond - Prahran"];
    [self.tramLocations addObject:@"79 - North Richmond - St Kilda Beach"];
    [self.tramLocations addObject:@"82 - Moonee Ponds - Footscray"];
    [self.tramLocations addObject:@"86 - Bundoora RMIT - Waterfront City Docklands"];
    [self.tramLocations addObject:@"95 - City (Spencer St) - Melbourne Museum"];
    [self.tramLocations addObject:@"96 - East Brunswick - St Kilda Beach"];
    [self.tramLocations addObject:@"109 - Box Hill - Port Melbourne"];
    [self.tramLocations addObject:@"112 - West Preston - St Kilda"];
    //[self.tramLocations sortUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
}


-(void) addBusLocations {
    
    [self.busLocations addObject:@"200 - City - Bulleen"];
    [self.busLocations addObject:@"200/1/3/5/7 combined - City - Bulleen - Doncaster Shoppingtown"];
    [self.busLocations addObject:@"200/203/205 combined - City - Bulleen - Doncaster Shoppingtown"];
    [self.busLocations addObject:@"201 - City - Doncaster Shoppingtown via Belmore Road"];
    [self.busLocations addObject:@"201/202/302 combined - City - Box Hill/Doncaster via Belmore Road, Freeway"];
    [self.busLocations addObject:@"202 - East Kew - Box Hill via Belmore Road"];
    [self.busLocations addObject:@"203 - City - Bulleen"];
    [self.busLocations addObject:@"205 - Melbourne University - Doncaster Shoppingtown via Kew Junction"];
    [self.busLocations addObject:@"207 - City - Donvale via Doncaster Road"];
    [self.busLocations addObject:@"215 - Caroline Springs - Highpoint SC"];
    [self.busLocations addObject:@"216 - Caroline Springs - Brighton Beach"];
    [self.busLocations addObject:@"216/219 combined - Caroline Springs/Sunshine Park - City - Brighton Beach/Gardenvale"];
    [self.busLocations addObject:@"219 - Sunshine Park - Gardenvale"];
    [self.busLocations addObject:@"220 - Sunshine - City - Gardenvale"];
    [self.busLocations addObject:@"223 - Yarraville - Highpoint SC"];
    [self.busLocations addObject:@"232 - Altona North - Queen Victoria Market "];
    [self.busLocations addObject:@"235 - City - Fishermans Bend via Williamstown Road "];
    [self.busLocations addObject:@"235/237/238 combined - City - Fishermans Bend"];
    [self.busLocations addObject:@"237 - City - Fishermans Bend via Lorimer Street "];
    [self.busLocations addObject:@"238 - City - Port Melbourne via Lorimer Street, Salmon Street "];
    [self.busLocations addObject:@"246 - Elsternwick - La Trobe University via Clifton Hill, St Kilda Junction"];
    [self.busLocations addObject:@"246/250 combined - Elsternwick/Garden City - La Trobe University via Clifton Hill"];
    [self.busLocations addObject:@"250 - Garden City - La Trobe University via City"];
    [self.busLocations addObject:@"250/251/253 combined - Garden City - City - Rathdowne St - LaTrobe Uni/Northland SC"];
    [self.busLocations addObject:@"251 - Garden City - Northland via City"];
    [self.busLocations addObject:@"253 - Garden City - North Carlton via City"];
    [self.busLocations addObject:@"270 - Box Hill - Ringwood via Mitcham"];
    [self.busLocations addObject:@"270/271 combined - Box Hill - Ringwood via Blackburn North"];
    [self.busLocations addObject:@"271 - Box Hill - Ringwood via Park Orchards"];
    [self.busLocations addObject:@"273 - The Pines - Nunawading"];
    [self.busLocations addObject:@"279 - Box Hill - Doncaster Shoppingtown via Middleborough Road"];
    [self.busLocations addObject:@"280 - Manningham Loop via Tunstall Square SC, Shoppingtown"];
    [self.busLocations addObject:@"281 - Templestowe to Deakin University"];
    [self.busLocations addObject:@"282 - Manningham Mover via Templestowe Village SC, Shoppingtown"];
    [self.busLocations addObject:@"284 - Doncaster Shoppingtown - Box Hill via Union Road"];
    [self.busLocations addObject:@"285 - Doncaster Shoppingtown - Camberwell via North Balwyn"];
    [self.busLocations addObject:@"286 - Box Hill - The Pines Shopping Centre via Blackburn Road"];
    [self.busLocations addObject:@"293 - Box Hill - Greensborough via Doncaster Shoppingtown "];
    [self.busLocations addObject:@"295 - Box Hill - The Pines via Doncaster, Templestowe"];
    [self.busLocations addObject:@"302 - City - Box Hill via Belmore Road, Freeway"];
    [self.busLocations addObject:@"303 - City - North Ringwood via Springfield Road "];
    [self.busLocations addObject:@"305 - City - The Pines SC via Andersons Creek Road"];
    [self.busLocations addObject:@"309 - City - Donvale via Reynolds Road (Freeway Exp) "];
    [self.busLocations addObject:@"313 - City (Russell Street) - Doncaster Park + Ride via Eastern Freeway and Kilby Road"];
    [self.busLocations addObject:@"315 - City (Russell Street) - Box Hill via Eastern Freeway, Greythorn Road"];
    [self.busLocations addObject:@"318 - City - Deep Creek "];
    [self.busLocations addObject:@"340 - City - Latrobe University via Eastern Freeway and Oriel Rd"];
    [self.busLocations addObject:@"364 - Warrandyte - Ringwood via Ringwood North"];
    [self.busLocations addObject:@"366 - Ringwood - Croydon via Croydon Hills"];
    [self.busLocations addObject:@"367 - Ringwood - Croydon via East Ringwood"];
    [self.busLocations addObject:@"400 - Sunshine - Laverton via Robinsons Road"];
    [self.busLocations addObject:@"401 - North Melbourne - University of Melbourne via Royal Melbourne Hospital"];
    [self.busLocations addObject:@"402 - Footscray - East Melbourne via North Melbourne"];
    [self.busLocations addObject:@"404 - Footscray - Moonee Ponds via Newmarket"];
    [self.busLocations addObject:@"406 - Keilor East - Footscray via Avondale Heights and Maribyrnong"];
    [self.busLocations addObject:@"407 - Highpoint SC - Avondale Heights via Maribyrnong"];
    [self.busLocations addObject:@"408 - St Albans - Highpoint SC via Sunshine, Maribyrnong"];
    [self.busLocations addObject:@"409 - Yarraville to Highpoint SC via Footscray"];
    [self.busLocations addObject:@"410 - Sunshine - Footscray via Ballarat Road"];
    [self.busLocations addObject:@"411 - Laverton - Footscray via Altona Meadows, Altona, Millers Road"];
    [self.busLocations addObject:@"411/412 combined - Laverton - Footscray via Altona Meadows, Altona, Altona Gate SC"];
    [self.busLocations addObject:@"412 - Laverton - Footscray via Altona Meadows, Altona, Mills Street"];
    [self.busLocations addObject:@"413 - Hoppers Crossing - Laverton via Old Geelong Rd, Point Cook"];
    [self.busLocations addObject:@"414 - Aircraft to Footscray via Geelong Road"];
    [self.busLocations addObject:@"415 - Laverton to Williamstown via Altona, North Williamstown"];
    [self.busLocations addObject:@"416 - Hoppers Crossing - Laverton via Sneydes Rd, Point Cook, Altona Meadows"];
    [self.busLocations addObject:@"417 - Laverton - Laverton North"];
    [self.busLocations addObject:@"418 - Caroline Springs Square Shopping Centre - St Albans"];
    [self.busLocations addObject:@"419 - St Albans - Watergardens Railway Station via Taylors Lakes"];
    [self.busLocations addObject:@"421 - St Albans - Watergardens Railway Station via Keilor Downs"];
    [self.busLocations addObject:@"422 - St Albans - Delahey "];
    [self.busLocations addObject:@"423 - St Albans - Deer Park Shopping Centre via Furlong Road"];
    [self.busLocations addObject:@"424 - St Albans - Deer Park Shopping Centre via Gillespie Road"];
    [self.busLocations addObject:@"425 - St Albans - Watergardens Railway Station via Delahey"];
    [self.busLocations addObject:@"431 - Yarraville - Kingsville via Somerville Road"];
    [self.busLocations addObject:@"432 - Newport - Yarraville via Altona Gate Shopping Centre"];
    [self.busLocations addObject:@"436 - Werribee - Hoppers Crossing"];
    [self.busLocations addObject:@"437 - Werribee - Hoppers Crossing"];
    [self.busLocations addObject:@"439 - Werribee - Werribee South"];
    [self.busLocations addObject:@"441 - Werribee - Westleigh Gardens"];
    [self.busLocations addObject:@"442 - Tarneit - Hoppers Crossing"];
    [self.busLocations addObject:@"443 - Werribee - South Ring Road"];
    [self.busLocations addObject:@"444 - Hoppers Crossing - Hoppers Crossing via Tarneit"];
    [self.busLocations addObject:@"445 - Werribee - Hoppers Crossing via Thames Boulevard, Werribee Plaza"];
    [self.busLocations addObject:@"446 - Laverton - Hoppers Crossing"];
    [self.busLocations addObject:@"447 - Werribee - Manor Lakes Shopping Centre"];
    [self.busLocations addObject:@"448 - Manor Lakes SC - Hoppers Crossing"];
    [self.busLocations addObject:@"449 - Werribee - Manor Lakes Shopping Centre"];
    [self.busLocations addObject:@"451 - Sunshine - Deer Park North via Ardeer"];
    [self.busLocations addObject:@"453 - Melton - Melton Station via Brookfield"];
    [self.busLocations addObject:@"454 - Sunshine - West Sunshine via Glengala Road"];
    [self.busLocations addObject:@"455 - Micasa Rise/Roslyn Park - Melton Station"];
    [self.busLocations addObject:@"456 - Sunshine - Melton via Caroline Springs"];
    [self.busLocations addObject:@"457 - Melton - Melton Station via Melton West"];
    [self.busLocations addObject:@"458 - Kurunjang - Melton Station"];
    [self.busLocations addObject:@"459 - Arnolds Creek to Melton Station via Westlake"];
    [self.busLocations addObject:@"460 - Watergardens - Caroline Springs"];
    [self.busLocations addObject:@"461 - Watergardens - Caroline Springs Shopping Centre"];
    [self.busLocations addObject:@"462 - Watergardens - Caroline Springs"];
    [self.busLocations addObject:@"465 - Essendon - Keilor Park via East Keilor"];
    [self.busLocations addObject:@"467 - Aberfeldie - Moonee Ponds via Holmes Road"];
    [self.busLocations addObject:@"468 - Essendon - Highpoint SC via Maribyrnong"];
    [self.busLocations addObject:@"471 - Williamstown - Sunshine via Newport &amp; Altona Gate Shopping Centre"];
    [self.busLocations addObject:@"472 - Williamstown - Moonee Ponds via Footscray"];
    [self.busLocations addObject:@"475 - Moonee Ponds - East Keilor via Niddrie"];
    [self.busLocations addObject:@"476 - Moonee Ponds - Hillside via Taylors Lakes &amp; Watergardens Railway Station"];
    [self.busLocations addObject:@"477 - Moonee Ponds - Broadmeadows via Essendon, Airport West, Gladstone Park"];
    [self.busLocations addObject:@"478 - Moonee Ponds - Melbourne Airport via Essendon, Airport West, Niddrie"];
    [self.busLocations addObject:@"478/479 combined - Moonee Ponds - Melbourne Airport via Essendon, Airport West, Niddrie"];
    [self.busLocations addObject:@"479 - Sunbury - Moonee Ponds via Melbourne Airport, Airport West"];
    [self.busLocations addObject:@"481 - Sunbury Railway Station - Mount Lion"];
    [self.busLocations addObject:@"483 - Sunbury - Moonee Ponds via Diggers Rest"];
    [self.busLocations addObject:@"484 - Broadmeadows - Roxburgh Park via Greenvale"];
    [self.busLocations addObject:@"485 - Sunbury Railway Station - Wilsons Lane"];
    [self.busLocations addObject:@"486 - Sunbury Railway Station - Rolling Meadows"];
    [self.busLocations addObject:@"487 - Sunbury Railway Station - Killara Heights"];
    [self.busLocations addObject:@"488 - Sunbury Railway Station - Jacksons Hill"];
    [self.busLocations addObject:@"489 - Sunbury Railway Station - Canterbury Hills"];
    [self.busLocations addObject:@"490 - Gowanbrae via Melrose Drive, Gowanbrae Drive"];
    [self.busLocations addObject:@"500 - Broadmeadows - Sunbury via Gladstone Park"];
    [self.busLocations addObject:@"501 - Moonee Ponds - Niddrie via Strathmore"];
    [self.busLocations addObject:@"503 - Essendon - East Brunswick via Albion Street"];
    [self.busLocations addObject:@"504 - Moonee Ponds - Clifton Hill via East Brunswick"];
    [self.busLocations addObject:@"505 - Moonee Ponds - Melbourne University via Parkville Gardens"];
    [self.busLocations addObject:@"506 - Moonee Ponds - Westgarth Station via Brunswick"];
    [self.busLocations addObject:@"508 - Alphington - Moonee Ponds via Northcote &amp; Brunswick"];
    [self.busLocations addObject:@"509 - West Brunswick - Sydney Road via Hope Street"];
    [self.busLocations addObject:@"510 - Essendon - Ivanhoe via Brunswick, Northcote, Thornbury"];
    [self.busLocations addObject:@"512 - Strathmore - East Coburg via Pascoe Vale South, Coburg West, Coburg"];
    [self.busLocations addObject:@"513 - Eltham - Glenroy via Greensborough or Lower Plenty"];
    [self.busLocations addObject:@"517 - Northland - St Helena via Viewbank, Greensborough"];
    [self.busLocations addObject:@"518 - Greensborough - St Helena West via St Helena"];
    [self.busLocations addObject:@"520 - Doreen to Greensborough"];
    [self.busLocations addObject:@"526 - Coburg - West Preston via Elizabeth Street"];
    [self.busLocations addObject:@"527 - Gowrie  - Northland via Murray Road"];
    [self.busLocations addObject:@"528 - Craigieburn Station - Craigieburn South"];
    [self.busLocations addObject:@"529 - Craigieburn - Craigieburn West via Craigieburn Rd"];
    [self.busLocations addObject:@"530 - Campbellfield - Coburg via Fawkner"];
    [self.busLocations addObject:@"531 - Upfield - North Coburg via Somerset Estate"];
    [self.busLocations addObject:@"532 - Craigieburn - Broadmeadows via Upfield Station"];
    [self.busLocations addObject:@"533 - Craigieburn - Craigieburn North via Royal Tce"];
    [self.busLocations addObject:@"534 - Glenroy to Coburg via Boundary Road, Sydney Road"];
    [self.busLocations addObject:@"535 - Craigieburn - Craigieburn West via Aitken Bvd"];
    [self.busLocations addObject:@"536 - Gowrie - Glenroy via Gowrie Park"];
    [self.busLocations addObject:@"538 - Somerset Estate - Broadmeadows via Camp Road"];
    [self.busLocations addObject:@"540 - Upfield - Broadmeadows via Coolaroo"];
    [self.busLocations addObject:@"541 - Roxburgh Park - Broadmeadows via Meadow Heights"];
    [self.busLocations addObject:@"542 - Roxburgh Park - Oak Park via Meadow Heights, Broadmeadows, Glenroy"];
    [self.busLocations addObject:@"544 - Craigieburn  - Roxburgh Park"];
    [self.busLocations addObject:@"546 - Heidelberg - Melbourne University - Queen Victoria Market via Clifton Hill and Carlton"];
    [self.busLocations addObject:@"548 - Kew (Cotham Road) - La Trobe University Bundoora"];
    [self.busLocations addObject:@"549 - Ivanhoe - Northland via Oriel Road"];
    [self.busLocations addObject:@"550 - Northland - La Trobe University via Waterdale Road"];
    [self.busLocations addObject:@"551 - Heidelberg - La Trobe University Interchange "];
    [self.busLocations addObject:@"552 - North East Reservoir - Northcote Plaza via High Street"];
    [self.busLocations addObject:@"553 - Preston - West Preston via Reservoir"];
    [self.busLocations addObject:@"554 - Thomastown via West Lalor (clockwise loop)"];
    [self.busLocations addObject:@"555 - Epping - Northland via Lalor, Thomastown, Reservoir"];
    [self.busLocations addObject:@"556 - Epping - Northland via Keon Park"];
    [self.busLocations addObject:@"557 - Thomastown via  West Lalor (anti-clockwise loop)"];
    [self.busLocations addObject:@"558 - Reservoir via North West Reservoir"];
    [self.busLocations addObject:@"559 - Thomastown via Darebin Drive"];
    [self.busLocations addObject:@"561 - Macleod - Coburg via La Trobe University"];
    [self.busLocations addObject:@"562 - Northland SC - Whittlesea via South Morang Station"];
    [self.busLocations addObject:@"564 - Bundoora RMIT - South Morang"];
    [self.busLocations addObject:@"565 - Kinglake - Whittlesea via Humevale"];
    [self.busLocations addObject:@"566 - Lalor - Northland via Plenty Road, Childs Road, Grimshaw Road"];
    [self.busLocations addObject:@"567 - Northcote - Regent via Northland"];
    [self.busLocations addObject:@"569 - Epping Plaza SC - South Morang"];
    [self.busLocations addObject:@"570 - Thomastown - RMIT Bundoora via Betula Avenue, Plenty Road"];
    [self.busLocations addObject:@"572 - University Hill to Doreen"];
    [self.busLocations addObject:@"573 - Bundoora RMIT - Mill Park Lakes - Palisades via South Morang Station"];
    [self.busLocations addObject:@"575 - Epping North - Thomastown via Epping"];
    [self.busLocations addObject:@"577 - Epping Plaza - South Morang Station via Findon Road"];
    [self.busLocations addObject:@"578 - Eltham - Warrandyte via Research, Kangaroo Ground, Warrandyte Road"];
    [self.busLocations addObject:@"578/579 combined - Eltham - Warrandyte via Research, Kangaroo Ground, Warrandyte Road"];
    [self.busLocations addObject:@"579 - Eltham - Warrandyte via Research, Research Warrandyte Road"];
    [self.busLocations addObject:@"580 - Diamond Creek - Eltham "];
    [self.busLocations addObject:@"582 - Eltham Town Service via Woodridge Estate"];
    [self.busLocations addObject:@"600 - Southland Shopping Centre - St Kilda Light Rail Station"];
    [self.busLocations addObject:@"600/922/923 combined - Southland SC - St Kilda Light Rail Station via Sandringham"];
    [self.busLocations addObject:@"601 - Huntingdale -  Monash University (Clayton)"];
    [self.busLocations addObject:@"605 - Gardenvale - City via Kooyong Road"];
    [self.busLocations addObject:@"606 - Elsternwick - Fishermans Bend"];
    [self.busLocations addObject:@"609 - Hawthorn to Fairfield via Kew"];
    [self.busLocations addObject:@"612 - Box Hill - Chadstone via Surrey Hills, Camberwell, Glen Iris"];
    [self.busLocations addObject:@"623 - Glen Waverley - St Kilda via Mount Waverley, Chadstone, Carnegie"];
    [self.busLocations addObject:@"624 - Kew - Oakleigh via Caulfield, Carnegie or Darling, and Chadstone"];
    [self.busLocations addObject:@"625 - Elsternwick - Chadstone via Ormond, Oakleigh"];
    [self.busLocations addObject:@"626 - Middle Brighton - Chadstone via McKinnon, Carnegie"];
    [self.busLocations addObject:@"630 - Elwood - Monash University via Gardenvale, Ormond &amp; Huntingdale"];
    [self.busLocations addObject:@"631 - Southland - Waverley Gardens via Clayton, Monash University"];
    [self.busLocations addObject:@"663 - Belgrave - Lilydale via Kallista, The Patch, Monbulk, Mt Evelyn"];
    [self.busLocations addObject:@"664 - Chirnside Park - Knox City via Croydon &amp; Bayswater"];
    [self.busLocations addObject:@"670 - Ringwood - Swinburne University via Croydon &amp; Chirnside Park"];
    [self.busLocations addObject:@"670/679 combined - Lilydale - Chirnside Park SC"];
    [self.busLocations addObject:@"671 - Croydon - Chirnside Park via Warrien Road, Patrick Street"];
    [self.busLocations addObject:@"672 - Croydon - Chirnside Park via Wonga Park, Croydon Hills"];
    [self.busLocations addObject:@"673 - Lilydale - Lillydale Lakes"];
    [self.busLocations addObject:@"675 - Chirnside Park - Mooroolbark via Manchester Road"];
    [self.busLocations addObject:@"676 - Lilydale Station via Maroondah Highway"];
    [self.busLocations addObject:@"677 - Lilydale Station - Chirnside Park via Switchback Road"];
    [self.busLocations addObject:@"679 - Chirnside Park Shopping Centre - Ringwood via Mt Evelyn, Montrose &amp; Canterbury Rd"];
    [self.busLocations addObject:@"680 - Lilydale - Mooroolbark via Lilydale East Estate, Lakeview Estate"];
    [self.busLocations addObject:@"681 - Lysterfield - Knox City via Wantirna, Scoresby, Rowville (clockwise)"];
    [self.busLocations addObject:@"682 - Lysterfield - Knox City via Wantirna, Scoresby, Rowville (anti-clockwise)"];
    [self.busLocations addObject:@"683 - Chirnside Park - Warburton via Lilydale Station, Seville, Yarra Junction"];
    [self.busLocations addObject:@"684 - Eildon - Melbourne via Lilydale Station"];
    [self.busLocations addObject:@"685 - Lilydale - Healesville via Lilydale Station, Coldstream, Yarra Glen"];
    [self.busLocations addObject:@"686 - Healesville - Badger Creek"];
    [self.busLocations addObject:@"687 - Chum Creek - Healesville"];
    [self.busLocations addObject:@"688 - Croydon - Upper Ferntree Gully via Olinda and Tremont"];
    [self.busLocations addObject:@"689 - Croydon - Montrose via Hawthory Road, Durham Road"];
    [self.busLocations addObject:@"690 - Croydon - Boronia via Kilsyth, Canterbury Gardens, Kilsyth South"];
    [self.busLocations addObject:@"691 - Boronia  - Waverley Gardens via Ferntree Gully, Stud Park"];
    [self.busLocations addObject:@"693 - Belgrave - Oakleigh via Ferntree Gully, Brandon Park"];
    [self.busLocations addObject:@"694 - Olinda - Belgrave via Sherbrooke Road"];
    [self.busLocations addObject:@"695 - Belgrave - Gembrook - Fountain Gate"];
    [self.busLocations addObject:@"696 - Olinda - Monbulk via Olinda - Monbulk Road"];
    [self.busLocations addObject:@"697 - Belgrave -  Belgrave South via Belgrave Heights"];
    [self.busLocations addObject:@"699 - Belgrave - Upwey "];
    [self.busLocations addObject:@"701 - Oakleigh - Bentleigh via Mackie Road, Brady Road"];
    [self.busLocations addObject:@"703 - Middle Brighton - Blackburn via Bentleigh, Clayton, Monash University (SMARTBUS Service)"];
    [self.busLocations addObject:@"704 - East Clayton - Oakleigh via Clayton, Huntingdale"];
    [self.busLocations addObject:@"705 - Mordialloc - Springvale via Braeside, Clayton South"];
    [self.busLocations addObject:@"706 - Mordialloc - Aspendale - Edithvale - Chelsea"];
    [self.busLocations addObject:@"708 - Carrum - Hampton via Southland"];
    [self.busLocations addObject:@"709 - Mordialloc - Waterways via Governor Rd"];
    [self.busLocations addObject:@"732 - Box Hill - Upper Ferntree Gully via Vermont South, Knox City, Mountain Gate"];
    [self.busLocations addObject:@"733 - Oakleigh - Box Hill via Clayton, Monash University, Mt Waverley"];
    [self.busLocations addObject:@"734 - Glen Iris - Glen Waverley "];
    [self.busLocations addObject:@"735 - Box Hill to Nunawading"];
    [self.busLocations addObject:@"736 - Mitcham - Blackburn via Vermont South, Glen Waverley, Forest Hill"];
    [self.busLocations addObject:@"737 - Croydon - Monash University via Boronia, Knox City Shopping Centre, Glen Waverley"];
    [self.busLocations addObject:@"738 - Mitcham - Knox City via Knox Private Hospital, Wantirna Secondary College"];
    [self.busLocations addObject:@"740 - Mitcham - Vermont East via Reserve Avenue, Churinga Avenue"];
    [self.busLocations addObject:@"742 - Eastland - Chadstone via Vermont South, Glen Waverley, Oakleigh"];
    [self.busLocations addObject:@"745 - Knox City - Bayswater -  Wantirna Primary School"];
    [self.busLocations addObject:@"753 - Glen Waverley - Bayswater via Wheelers Hill, Knoxfield, Boronia"];
    [self.busLocations addObject:@"754 - Rowville - Glen Waverley via Caulfield Grammar, Wheelers Hill"];
    [self.busLocations addObject:@"755 - Bayswater - Knox City via Basin, Boronia, Ferntree Gully"];
    [self.busLocations addObject:@"757 - Knox City - Scoresby via Old Orchards Drive"];
    [self.busLocations addObject:@"758 - Knox City - Knoxfield via Wallace Road"];
    [self.busLocations addObject:@"765 - Mitcham - Box Hill via Brentford Square, Forest Hill, Blackburn"];
    [self.busLocations addObject:@"766 - Box Hill - Burwood via Surrey Hills"];
    [self.busLocations addObject:@"767 - Southland - Box Hill via Chadstone, Jordanville, Deakin University"];
    [self.busLocations addObject:@"768 - Box Hill - Deakin University via Canterbury Rd (Effective from 09/07/2012)"];
    [self.busLocations addObject:@"770 - Frankston - Karingal via Ashleigh Avenue"];
    [self.busLocations addObject:@"771 - Frankston - Langwarrin via Karingal"];
    [self.busLocations addObject:@"772 - Frankston - Eliza Heights"];
    [self.busLocations addObject:@"773 - Frankston - Frankston South via Kars Street"];
    [self.busLocations addObject:@"774 - Frankston - Delacombe Park"];
    [self.busLocations addObject:@"775 - Frankston - Lakewood via Heatherhill Road"];
    [self.busLocations addObject:@"776 - Frankston - Pearcedale via Baxter"];
    [self.busLocations addObject:@"777 - Karingal Hub Shopping Centre - McClelland Drive"];
    [self.busLocations addObject:@"778 - Kananook - Carrum Downs via Lathams Rd"];
    [self.busLocations addObject:@"779 - Frankston - Belvedere via Kananook"];
    [self.busLocations addObject:@"780 - Frankston - Carrum via Seaford"];
    [self.busLocations addObject:@"781 - Frankston - Mount Martha via Mt Eliza, Mornington"];
    [self.busLocations addObject:@"781/784/785 combined - Frankston - Mt Eliza - Mornington East/Mt Martha"];
    [self.busLocations addObject:@"782 - Frankston - Flinders via Coolart Road, Hastings"];
    [self.busLocations addObject:@"782/783 combined - Frankston - Coolart Rd - Hastings/Flinders"];
    [self.busLocations addObject:@"783 - Frankston - Hastings via Coolart Road"];
    [self.busLocations addObject:@"784 - Frankston - Osborne via Mt Eliza, Mornington"];
    [self.busLocations addObject:@"785 - Frankston - Mornington East via Mt Eliza / Mornington"];
    [self.busLocations addObject:@"786 - Rye to St Andrews Beach"];
    [self.busLocations addObject:@"787 - Sorrento - Safety Beach"];
    [self.busLocations addObject:@"788 - Frankston - Portsea via Dromana, Rosebud, Sorrento"];
    [self.busLocations addObject:@"789 - Frankston - Cranbourne West via Karingal, Langwarrin"];
    [self.busLocations addObject:@"789/790/791 combined - Frankston - Cranbourne West via Karingal, Langwarrin"];
    [self.busLocations addObject:@"790 - Frankston - Cranbourne West via Karingal, Langwarrin, Southgateway"];
    [self.busLocations addObject:@"791 - Frankston - Cranbourne West via Karingal, Langwarrin"];
    [self.busLocations addObject:@"795 - Warneet - Cranbourne"];
    [self.busLocations addObject:@"796 - Cranbourne - Clyde (School Days Only)"];
    [self.busLocations addObject:@"797 - Cranbourne Town Service via Cranbourne Station"];
    [self.busLocations addObject:@"799 - Cranbourne - Cranbourne North via Merinda Park Station"];
    [self.busLocations addObject:@"800 - Dandenong - Chadstone via Princes Highway, Oakleigh"];
    [self.busLocations addObject:@"802 - Dandenong - Chadstone via Mulgrave, Oakleigh"];
    [self.busLocations addObject:@"802/804/862 combined - Dandenong - Chadstone via Mulgrave, Oakleigh"];
    [self.busLocations addObject:@"804 - Dandenong - Chadstone via Wheelers Hill, Oakleigh"];
    [self.busLocations addObject:@"811 - Dandenong - Brighton via Heatherton Road, Springvale"];
    [self.busLocations addObject:@"811/812 combined - Dandenong - Brighton via Southland SC"];
    [self.busLocations addObject:@"812 - Dandenong - Brighton via Parkmore Shopping Centre"];
    [self.busLocations addObject:@"813 - Dandenong - Waverley Gardens"];
    [self.busLocations addObject:@"814 - Springvale South - Dandenong via Waverley Gardens Shopping Centre, Springvale"];
    [self.busLocations addObject:@"815 - Dandenong - Noble Park"];
    [self.busLocations addObject:@"821 - Southland - Clayton via Heatherton"];
    [self.busLocations addObject:@"822 - Chadstone - Sandringham via Murrumbeena &amp; Southland"];
    [self.busLocations addObject:@"823 - North Brighton - Southland via Moorabbin"];
    [self.busLocations addObject:@"824 - Moorabbin - Keysborough via Clayton, Westall"];
    [self.busLocations addObject:@"825 - Moorabbin - Southland via Black Rock &amp; Mentone"];
    [self.busLocations addObject:@"828 - Hampton - Berwick Station via Southland SC, Dandenong"];
    [self.busLocations addObject:@"831 - Berwick Station - Kingsmere Estate via Casey Hospital"];
    [self.busLocations addObject:@"832 - Frankston - Carrum Downs via Kananook, McCormicks Road"];
    [self.busLocations addObject:@"833 - Frankston - Carrum Downs via The Pines, Lyrebird Drive"];
    [self.busLocations addObject:@"834 - Berwick - Narre Warren Circle via Berwick North, Narre Warren South"];
    [self.busLocations addObject:@"835 - Berwick - Narre Warren Circle via Narre Warren South, Berwick North"];
    [self.busLocations addObject:@"836 - Berwick Station - Eden Rise SC via Bridgewater Estate"];
    [self.busLocations addObject:@"837 - Berwick Station - Beaconsfield East via Brisbane St"];
    [self.busLocations addObject:@"838 - Fountain Gate - Emerald via Beaconsfield, Berwick"];
    [self.busLocations addObject:@"839 - Berwick Station - Berwick North via Harkaway Rd"];
    [self.busLocations addObject:@"840 - Gembrook - Pakenham"];
    [self.busLocations addObject:@"841 - Narre Warren North - Cranbourne via Narre Warren, Cranbourne North"];
    [self.busLocations addObject:@"842 - Fountain Gate - Endeavour Hills"];
    [self.busLocations addObject:@"843 - Dandenong - Mossgiel Park via Shetland Street"];
    [self.busLocations addObject:@"843/845/849/861 - Dandenong - Endeavour Hills via Doveton"];
    [self.busLocations addObject:@"844 - Dandenong - Doveton via McCrae Street"];
    [self.busLocations addObject:@"845 - Dandenong - Mossgiel Park via John Fawkner Drive"];
    [self.busLocations addObject:@"846 - Berwick Station - Eden Rise SC via Bemersyde Rd"];
    [self.busLocations addObject:@"847 - Berwick Station - Casey Central SC via Glasscocks Rd"];
    [self.busLocations addObject:@"848 - Dandenong - Brandon Park Shopping Centre via Waverley Gardens Shopping Centre"];
    [self.busLocations addObject:@"849 - Dandenong - Mossgiel Park via Gleneagles Drive"];
    [self.busLocations addObject:@"850 - Dandenong - Glen Waverley via Mulgrave, Brandon Park"];
    [self.busLocations addObject:@"857 - Chelsea - Dandenong via Patterson Lakes"];
    [self.busLocations addObject:@"858 - Edithvale - Aspendale Gardens via Chelsea"];
    [self.busLocations addObject:@"861 - Dandenong - Endeavour Hills via Thomas Mitchell Drive"];
    [self.busLocations addObject:@"862 - Dandenong - Chadstone via North Dandenong, Oakleigh"];
    [self.busLocations addObject:@"885 - Glen Waverley - Springvale via Wanda Street"];
    [self.busLocations addObject:@"886 - Rosebud - Chisholm TAFE Rosebud Campus"];
    [self.busLocations addObject:@"891 - Lynbrook  - Fountain Gate SC via Hallam Station and Hallam Gardens"];
    [self.busLocations addObject:@"892 - Casey Central SC - Dandenong via Hampton Park"];
    [self.busLocations addObject:@"893 - Cranbourne - Dandenong via Lynbrook, Hampton Park, Hallam Station"];
    [self.busLocations addObject:@"894 - Amberly Park  - Hallam via Hampton Park"];
    [self.busLocations addObject:@"895 - Narre Warren South - Fountain Gate SC via Narre Warren Station"];
    [self.busLocations addObject:@"896 - Cranbourne Station - Cranbourne East (TRAINLINK Service) Circular Route"];
    [self.busLocations addObject:@"897 - Cranbourne Station - Central Parkway - Cranbourne Station"];
    [self.busLocations addObject:@"898 - Archers Field Drive - Cranbourne via Cranbourne Station"];
    [self.busLocations addObject:@"900 - Rowville - Caulfield via Monash University, Chadstone (SMARTBUS Service)"];
    [self.busLocations addObject:@"901 - Frankston - Melbourne Airport (SMARTBUS Service)"];
    [self.busLocations addObject:@"902 - Chelsea - Airport West (SMARTBUS Service)"];
    [self.busLocations addObject:@"903 - Altona to Mordialloc (SMARTBUS Service)"];
    [self.busLocations addObject:@"905 - City - The Pines SC via Templestowe (SMARTBUS Service) "];
    [self.busLocations addObject:@"906 - City - Warrandyte Bridge (SMARTBUS Service) "];
    [self.busLocations addObject:@"907 - City - Mitcham via Doncaster Road (SMARTBUS Service) "];
    [self.busLocations addObject:@"907/908 combined - City - Doncaster Park + Ride "];
    [self.busLocations addObject:@"908 - City - The Pines via King Street (SMARTBUS Service) "];
    [self.busLocations addObject:@"922 - Southland Shopping Centre - St Kilda Light Rail Station"];
    [self.busLocations addObject:@"923 - Southland Shopping Centre - St Kilda Light Rail Station"];
    [self.busLocations addObject:@"924 - Pakenham Station - Pakenham South"];
    [self.busLocations addObject:@"925 - Pakenham Station - Lakeside/Botanic Drive"];
    [self.busLocations addObject:@"926 - Pakenham - Fountain Gate Shopping Centre"];
    [self.busLocations addObject:@"927 - Pakenham Town Service via Meadowvale Village"];
    [self.busLocations addObject:@"928 - Pakenham - Pakenham South via Henry Street"];
    [self.busLocations addObject:@"929 - Pakenham Town Service via Army Road"];
}

-(NSInteger)getNumberOfStationsForSelectedTransport:(NSInteger)selectedTransportType {
    if(selectedTransportType == SELECTED_TRANSPORT_TRAIN) {
        return [self.trainLocations count];
    } else if(selectedTransportType == SELECTED_TRANSPORT_BUS)  {
         return [self.busLocations count];
    } else  {
         return [self.tramLocations count];
    }
}

-(NSMutableArray*)getStationsForSelectedTransport:(NSInteger)selectedTransportType {
    if(selectedTransportType == SELECTED_TRANSPORT_TRAIN) {

       
        return self.trainLocations;
    } else if(selectedTransportType == SELECTED_TRANSPORT_BUS)  {
       // [self.busLocations sortUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
        return self.busLocations ;
    } else  {
        //[self.tramLocations sortUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
        return self.tramLocations;
    }
}

@end
